name: CI/CD Pipeline for TrailBlazer

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull request targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Define Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Lint the code
        run: |
          pip install flake8
          flake8 . --max-line-length=120

  deploy:
    runs-on: ubuntu-latest
    needs: build # Only run if the build job is successful
    if: success() # Only run if the build job is successful

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable (optional step)
        run: |
          pyinstaller --onefile trailblazer.py

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v2
        with:
          name: trailblazer-build
          path: dist/

      - name: Deploy to server or cloud (optional)
        run: |
          echo "Deploying app..."
